apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1) Pull in the “base” folder for workload-A:
bases:
  - ../../base

# 2) List only the workload-specific resources to overlay in “prod”:
resources:
  - deployment.yaml
  - service.yaml

# 3) (Optional) any additional patches (config, secrets, etc.)
commonLabels:
  workload: workload-A
  environment: prod

