apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkhan-nginx
spec:
  selector:
    matchLabels:
      run: mkhan-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: mkhan-nginx
    spec:
      containers:
      - name: mkhan-nginx
        image: nginx
